package com.example.hikingapp.ui.model

val hikes = listOf(
    Hike("Matterhorn Trail", 45.9763, 7.6586,
        "Famous hike near Zermatt with breathtaking views of the Matterhorn.",
        riskLevel = "High",
        insuranceUrl = "https://insurance.example/matterhorn",
        mark = 4.9),
    Hike("Eiger Trail", 46.5803, 8.0059,
        "Iconic hike below the north face of the Eiger.",
        riskLevel = "Moderate",
        insuranceUrl = "https://insurance.example/eiger",
        mark = 4.7),
    Hike("Oeschinensee Lake Hike", 46.4981, 7.7266,
        "Beautiful turquoise alpine lake near Kandersteg.",
        riskLevel = "Low",
        insuranceUrl = "https://insurance.example/oeschinensee",
        mark = 4.8),
    Hike("Aletsch Glacier Trail", 46.4436, 8.0776,
        "Panoramic views of the largest glacier in the Alps.",
        riskLevel = "High",
        insuranceUrl = "https://insurance.example/aletsch",
        mark = 4.6),
    Hike("Creux du Van", 46.9425, 6.7287,
        "Natural rocky amphitheatre in the Jura mountains.",
        riskLevel = "Moderate",
        insuranceUrl = "https://insurance.example/creuxduvan",
        mark = 4.4),
    Hike("Rigi Panorama Trail", 47.0565, 8.4656,
        "Panoramic ridge hike with Lake Lucerne views.",
        riskLevel = "Low",
        insuranceUrl = "https://insurance.example/rigi",
        mark = 4.5),
    Hike("Säntis Hike", 47.2490, 9.3430,
        "Highest mountain in the Alpstein massif.",
        riskLevel = "Moderate",
        insuranceUrl = "https://insurance.example/santis",
        mark = 4.3),
    Hike("Pilatus Hike", 46.9790, 8.2520,
        "Steep trails and legends above Lucerne.",
        riskLevel = "Moderate",
        insuranceUrl = "https://insurance.example/pilatus",
        mark = 4.6),
    Hike("Schynige Platte to First", 46.6581, 7.9378,
        "Spectacular ridge hike above Interlaken.",
        riskLevel = "Moderate",
        insuranceUrl = "https://insurance.example/schynige",
        mark = 4.9),
    Hike("Lauterbrunnen Valley Walk", 46.5931, 7.9078,
        "Valley of 72 waterfalls.",
        riskLevel = "Low",
        insuranceUrl = "https://insurance.example/lauterbrunnen",
        mark = 4.8),
    Hike("Grindelwald First Cliff Walk", 46.6243, 8.0422,
        "Suspension bridge & alpine views near First.",
        riskLevel = "Low",
        insuranceUrl = "https://insurance.example/firstcliff",
        mark = 4.7),
    Hike("Hardergrat Trail", 46.7065, 7.8793,
        "Narrow ridge hike for thrill seekers.",
        riskLevel = "High",
        insuranceUrl = "https://insurance.example/hardergrat",
        mark = 2.8),
    Hike("Pizol Five Lakes Hike", 46.9894, 9.4064,
        "Tour through turquoise alpine lakes.",
        riskLevel = "Moderate",
        insuranceUrl = "https://insurance.example/pizol",
        mark = 4.8),
    Hike("Trift Bridge Hike", 46.7087, 8.3234,
        "Suspension bridge over glacial valley.",
        riskLevel = "Moderate",
        insuranceUrl = "https://insurance.example/trift",
        mark = 4.2),
    Hike("Blausee Nature Park", 46.5394, 7.6641,
        "Short family hike to a crystal-blue lake.",
        riskLevel = "Low",
        insuranceUrl = "https://insurance.example/blausee",
        mark = 3.9),
    Hike("Arosa Weisshorn", 46.7787, 9.6802,
        "Trail from Arosa to the Weisshorn summit.",
        riskLevel = "Moderate",
        insuranceUrl = "https://insurance.example/weisshorn",
        mark = 4.3),
    Hike("Monte San Salvatore", 45.9858, 8.9523,
        "Panoramic Lugano hike.",
        riskLevel = "Low",
        insuranceUrl = "https://insurance.example/sansalvatore",
        mark = 4.4),
    Hike("Monte Generoso", 45.9333, 9.0167,
        "Ticino classic with border views.",
        riskLevel = "Low",
        insuranceUrl = "https://insurance.example/montegeneroso",
        mark = 4.5),
    Hike("Brienzer Rothorn", 46.7561, 8.0506,
        "Sharp ridges and Lake Brienz below.",
        riskLevel = "Moderate",
        insuranceUrl = "https://insurance.example/brienzerrothorn",
        mark = 3.8),
    Hike("Dent de Vaulion", 46.6687, 6.3306,
        "Jura hike with Lake Geneva views.",
        riskLevel = "Low",
        insuranceUrl = "https://insurance.example/vaulion",
        mark = 3.5),
    Hike("Glacier 3000 Peak Walk", 46.3539, 7.2165,
        "Suspension bridge between peaks.",
        riskLevel = "Moderate",
        insuranceUrl = "https://insurance.example/glacier3000",
        mark = 4.6),
    Hike("Uetliberg to Felsenegg", 47.3510, 8.4910,
        "Zurich skyline trail.",
        riskLevel = "Low",
        insuranceUrl = "https://insurance.example/uetliberg",
        mark = 3.2),
    Hike("Panoramaweg Stoos Ridge", 46.9765, 8.6664,
        "Breathtaking ridge above Lake Lucerne.",
        riskLevel = "Moderate",
        insuranceUrl = "https://insurance.example/stoos",
        mark = 4.7),
    Hike("Engstligenalp Waterfalls", 46.4411, 7.6086,
        "Second highest waterfalls in Switzerland.",
        riskLevel = "Low",
        insuranceUrl = "https://insurance.example/engstligen",
        mark = 4.4),
    Hike("Gornergrat", 45.9836, 7.7856,
        "Matterhorn views from panoramic ridge.",
        riskLevel = "Low",
        insuranceUrl = "https://insurance.example/gornergrat",
        mark = 4.9),
    Hike("Rochers-de-Naye", 46.4361, 6.9794,
        "Above Montreux with Lake Geneva panorama.",
        riskLevel = "Low",
        insuranceUrl = "https://insurance.example/naye",
        mark = 3.7),
    Hike("Bachalpsee Lake Hike", 46.6613, 8.0458,
        "Postcard lake near Grindelwald First.",
        riskLevel = "Low",
        insuranceUrl = "https://insurance.example/bachalpsee",
        mark = 4.8),
    Hike("Faulhornweg", 46.6789, 8.0489,
        "Scenic ridge trail via Faulhorn peak.",
        riskLevel = "Moderate",
        insuranceUrl = "https://insurance.example/faulhorn",
        mark = 4.1),
    Hike("Jungfraujoch Panorama Trail", 46.5476, 7.9806,
        "High-altitude trail from Jungfraujoch station.",
        riskLevel = "High",
        insuranceUrl = "https://insurance.example/jungfraujoch",
        mark = 4.5),
    Hike("Badly Rated Trail Example", 46.9000, 8.0000,
        "This hike is poorly maintained and prone to erosion.",
        riskLevel = "High",
        insuranceUrl = "https://insurance.example/badtrail",
        mark = 1.4)  // a low-mark example
)
